name: generate-lambda-package

on: [push, pull_request]

jobs:
  generate-lambda-package:
    strategy:
      matrix:
        platform:
          - ubuntu-latest
    name: Format and lint ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out git repo
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 12
      - name: Run npm command
        run: |
          mkdir nodejs
          npm install --production
          npm pack
          tarball=$(npm list — depth 0 | sed ‘s/@/-/g; s/ .*/.tgz/g; 1q;’); tar -tf $tarball | sed ‘s/^package\\///’ | zip -@r package; rm $tarball
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: lambda-layer-zip
          path: package.zip
