name: generate-lambda-package

on: [push, pull_request]

jobs:
  generate-lambda-package:
    name: Generate lambda package
    runs-on: ubuntu-latest
    steps:
      - name: Check out git repo
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 12
      - name: Package the library
        run: |
          npm install --production
          npm pack
          tar xzf blue-button-1.10.1.tgz
          mv package nodejs
          zip -r package.zip nodejs
      - name: Archive lambda layer zip
        uses: actions/upload-artifact@v3
        with:
          name: lambda-layer-zip
          path: package.zip
